### ISSUE TITLE
App crash after scan

### ISSUE THREAD

**Issue by safwanmalik** [Jumio/mobile-cordova#1]
Hi, 
I have done the integration last time using iOS SDK and now with a custom plugin to integrate with cordova project. Now since you have build Cordova integrated lib, I have try to compile with my cordova project and it crash due to to the callbackId. Can someone help.

**Comment by safwanmalik** [comment]
Hi,
To update, I manage to fixed the crash issue by amend "_callbackId" to "self.callbackId". Now I encounter one more issue whereby the localized file changes not taking effect in the MobileSDK.

**Comment by JumioMobileTeam** [comment]
There seems to be a problem using the variable directly, we will also change this on our end.  Please move on using “self.callbackId” like you mentioned.

Localisation needs to be done in the native projects of your Cordova application.
For iOS follow this chapter of our integration guide: https://github.com/Jumio/mobile-sdk-ios#localization
For Android follow this chapter of our integration guide: https://github.com/Jumio/mobile-sdk-android#localizing-labels

best regards,
Jumio Mobile Team

**Comment by MHDMAM** [comment]
> For iOS follow this chapter of our integration guide: https://github.com/Jumio/mobile-sdk-ios#localization

I have tried to implement localization this way and still showing the original text.

**Comment by JumioMobileTeam** [comment]
A quick check on our side showed it works without problems. After adding the localization file to the Xcode project, you also need to mark it as Localizable. Following this, you can add other languages for the project. This are settings specific to iOS, please walk through [Apple's localization guide](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html#//apple_ref/doc/uid/10000171i-CH5-SW1)

best regards,
Jumio Mobile Team

**Comment by JumioMobileTeam** [comment]
If you have further questions please contact Jumio Customer Service at support@jumio.com or https://support.jumio.com.
