### ISSUE TITLE
Jumio Cordova upgrade to latest sdk

### ISSUE THREAD

**Issue by marshall86** [Jumio/mobile-cordova#11]
Hi,

I'm integrating Jumio in my Ionic and Capacitor project using this library https://github.com/danielzen/jumio-cordova, I don't know if you are involved in its maintenance but I would like to upgrade it to the latest SDK as currently jumio-cordova is using the sdk 3.6.0

Can you help me with this? Can you do the upgrade for me or can you help me to understand how to do it?

Much appreciate your help.

**Comment by bratapfelmus** [comment]
Hello @marshall86 
the repository and its contents -- https://github.com/danielzen/jumio-cordova -- are not maintained by Jumio. 

Our current SDK version is 4.0.0. (Though the update to 4.0.0 involves backend changes that require some effort.) You could also update to the second to last version, 3.9.2, first which might make things easier. 

I suggest you have a closer look at this Jumio repository and the pervious versions in between 3.6.0 and 3.9.2. If any specific questions pop up, let us know.

**Comment by marshall86** [comment]
Much appreciate your feedback, thanks a lot. I need the integration with capacitor, can you help me? It's quite urgent..

**Comment by bratapfelmus** [comment]
Hello @marshall86 once again -- if you have any specific questions, feel free to ask.

**Comment by marshall86** [comment]
thanks again.. my question is: can you make your library working on Capacitor? capacitor is the new standard for ionic since version 4

**Comment by bratapfelmus** [comment]
Yes, it should be possible. 
Jumio provides and maintains a Cordova plugin. Compatibility with Ionic Capacitor isn't something that is tested regularly, but it should work fine in theory.

If you need to install the plugin with npm, please check out --> https://www.npmjs.com/package/jumio-cordova-plugin-mobilesdk

**Comment by marshall86** [comment]
I managed to upgrade to 3.8 and it seems to be working but if I try to upgrate to 3.9 or latest I have some errors while building the app in Android because of some kotlin dependencies, do you have any guide regarding this kind of upgrade?

**Comment by marshall86** [comment]
I have another question @bratapfelmus .. I'm using the Jumio ionic plugin you told me, I installed it on ios (version 3.9.2) and in the simulator i can see the id/document scan that start but when I run it on a real device I get "the netverify sdk is not initialized yet" and "the document verification sdk is not initialized yet" errors, can you help me with this pls?

**Comment by bratapfelmus** [comment]
Hello @marshall86 as stated above, compatibility with Ionic Capacitor isn't something we actively test for, so it's difficult to say without context. 

Those errors are thrown whenever `initNetverify` / `initDocumentVerification` functions either aren't called at all or the SDK wasn't initialized successfully. If that is the case and the init failed for whatever reason, there should be an error returned you could check for.

**Comment by marshall86** [comment]
checking if this https://github.com/Jumio/mobile-sdk-ios/blob/master/docs/known_issues.md#sdk-version-not-compatible-after-xcode-13-update might be the problem, I saw your reply on another comment.

**Comment by bratapfelmus** [comment]
@marshall86 Are you using Xcode?

**Comment by marshall86** [comment]
yes

**Comment by bratapfelmus** [comment]
The error you should be getting when trying to initialize, if this is in fact an issue with Xcode 13 build options is `SDKVersionNotCompatibleException: ...`

**Comment by marshall86** [comment]
In the simulator I have no errors so hopefully that setting will fix the issue

**Comment by marshall86** [comment]
FYI it worked

**Comment by marshall86** [comment]
Good morning @bratapfelmus, hope I'm not bothering you too much :D .
I'm facing an issue on ios, in the liveness frame the text in the footer is not translated and I can see "Iproov_PromptLIvenessAlignFace" or a similar message for the complete or "move closer" . 
All the other messages are correctly translated, can you help me with this please? Still using sdk 3.9.2. 
Thanks

**Comment by bratapfelmus** [comment]
Hello @marshall86 
the project needs to be Localized to English, not just system language, see also --> https://github.com/Jumio/mobile-cordova/issues/8#issuecomment-880662767

**Comment by marshall86** [comment]
Thanks @bratapfelmus , appreciate your help.

I'm trying to upgrade from 3.9.2 to 4.0.0 using your ionic cordova plugin but the JumioMobileSdk.java file has many errors .. Syntax errors and references to:

import com.jumio.cordova.demo.R;
import com.jumio.defaultui.JumioActivity;
import com.jumio.sdk.JumioSDK;
import com.jumio.sdk.credentials.JumioCredentialInfo;
import com.jumio.sdk.exceptions.PlatformNotSupportedException;
import com.jumio.sdk.result.JumioCredentialResult;
import com.jumio.sdk.result.JumioFaceResult;
import com.jumio.sdk.result.JumioIDResult;
import com.jumio.sdk.result.JumioResult;

can you check it out please?

**Comment by bratapfelmus** [comment]
@marshall86 
could you be more specific? Not entirely sure what the question is.

**Comment by marshall86** [comment]
After installing jumio-cordova-plugin-mobilesdk:4.0.0, i run the project in Android studio through capacitor and as soon as I create the build I get some errors in the JumioMobileSdk.java file

This is the file:

`/*
 * Copyright 2017 Jumio Corporation
 * All rights reserved
 */

package com.jumio.mobilesdk;

import com.jumio.cordova.demo.R;
import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.util.Log;

import com.jumio.defaultui.JumioActivity;
import com.jumio.sdk.JumioSDK;
import com.jumio.sdk.credentials.JumioCredentialInfo;
import com.jumio.sdk.exceptions.PlatformNotSupportedException;
import com.jumio.sdk.result.JumioCredentialResult;
import com.jumio.sdk.result.JumioFaceResult;
import com.jumio.sdk.result.JumioIDResult;
import com.jumio.sdk.result.JumioResult;

import org.apache.cordova.CallbackContext;
import org.apache.cordova.CordovaPlugin;
import org.apache.cordova.PluginResult;
import org.apache.cordova.PluginResult.Status;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

public class JumioMobileSDK extends CordovaPlugin {

    private static String TAG = "JumioMobileSDK";
    private static final int PERMISSION_REQUEST_CODE = 301;
    private final static int REQUEST_CODE = 101;

    private static final String ACTION_INIT = "initialize";
    private static final String ACTION_START = "start";

    private CallbackContext callbackContext;
    private boolean initiateSuccessful = false;

    @Override
    public boolean execute(String action, JSONArray args, CallbackContext callbackContext) throws JSONException {
        PluginResult result = null;
        this.callbackContext = callbackContext;

        if (action.equals(ACTION_INIT)) {
            initialize(args);
            result = new PluginResult(Status.NO_RESULT);
            result.setKeepCallback(false);
            return true;
        } else if (action.equals(ACTION_START)) {
            start(args);
            result = new PluginResult(Status.NO_RESULT);
            result.setKeepCallback(true);
            return true;
        } else {
            result = new PluginResult(Status.INVALID_ACTION);
            callbackContext.error("Invalid Action");
            return false;
        }
    }

    private void initialize(JSONArray data) {
        if (!JumioSDK.isSupportedPlatform(cordova.getActivity())) {
            showErrorMessage("This platform is not supported.");
            return;
        }

        try {
            if (data.isNull(0) || data.isNull(1)) {
                showErrorMessage("Missing required parameters one-time session authorization token or dataCenter.");
                return;
            }

            final String authorizationToken = data.getString(0);
            final String dataCenter = data.getString(1);

            final Intent intent = new Intent(cordova.getActivity(), JumioActivity.class);
            intent.putExtra(JumioActivity.EXTRA_TOKEN, authorizationToken);
            intent.putExtra(JumioActivity.EXTRA_DATACENTER, dataCenter);

            //The following intent extra can be used to customize the Theme of Default UI
            intent.putExtra(JumioActivity.EXTRA_CUSTOM_THEME, R.style.AppThemeCustomJumio);

            cordova.getActivity().startActivityForResult(intent, REQUEST_CODE);

        } catch (JSONException e) {
            showErrorMessage("Invalid parameters: " + e.getLocalizedMessage());
        }
    }

    private void start(JSONArray data) {
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                try {
                    checkPermissionsAndStart();
                } catch (Exception e) {
                    showErrorMessage("Error starting the Jumio SDK: " + e.getLocalizedMessage());
                }
            }
        };

        this.cordova.setActivityResultCallback(this);
        this.cordova.getActivity().runOnUiThread(runnable);
    }

    // Permissions
    private void checkPermissionsAndStart() {
        if (!JumioSDK.hasAllRequiredPermissions(cordova.getActivity().getApplicationContext())) {
            //Acquire missing permissions.
            String[] mp = JumioSDK.getMissingPermissions(cordova.getActivity().getApplicationContext());

            cordova.requestPermissions(this, PERMISSION_REQUEST_CODE, mp);
        }
    }

    @Override
    public void onRequestPermissionResult(int requestCode, String[] permissions, int[] grantResults) throws
            JSONException {
        boolean allGranted = true;
        for (int grantResult : grantResults) {
            if (grantResult != PackageManager.PERMISSION_GRANTED) {
                allGranted = false;
                break;
            }
        }

        if (!allGranted) {
            showErrorMessage("You need to grant all required permissions to continue");
            super.onRequestPermissionResult(requestCode, permissions, grantResults);
        }
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == REQUEST_CODE) {
            if (data == null) {
                return;
            }

            final JumioResult jumioResult = (JumioResult) data.getSerializableExtra(JumioActivity.EXTRA_RESULT);

            if (jumioResult != null && jumioResult.isSuccess()) {
                sendScanResult(jumioResult);
            } else {
                sendCancelResult(jumioResult);
            }
        }
    }

    private void sendScanResult(final JumioResult jumioResult) {
        final String accountId = jumioResult.getAccountId();
        final List<JumioCredentialInfo> credentialInfoList = jumioResult.getCredentialInfos();

        final JSONObject result = new JSONObject();
        final ArrayList<JSONObject> credentialsArray = new ArrayList<>();


        if (credentialInfoList != null) {
            try {
                if (accountId != null) {
                    result.put("accountId", accountId);
                }
            } catch (JSONException e) {
                showErrorMessage("Result could not be sent: " + e.getLocalizedMessage());
            }

            for (JumioCredentialInfo credentialInfo : credentialInfoList) {
                final JumioCredentialResult jumioCredentialResult = jumioResult.getResult(credentialInfo);
                final JSONObject credentialMap = new JSONObject();
                try {
                    credentialMap.put("credentialId", credentialInfo.getId());
                    credentialMap.put("credentialCategory", credentialInfo.getCategory().toString());


                    if (jumioCredentialResult instanceof JumioIDResult) {
                        final JumioIDResult idResult = (JumioIDResult) jumioCredentialResult;
                        credentialMap.put("selectedCountry", idResult.getCountry());
                        credentialMap.put("selectedDocumentType", idResult.getIdType());
                        credentialMap.put("idNumber", idResult.getDocumentNumber());
                        credentialMap.put("personalNumber", idResult.getPersonalNumber());
                        credentialMap.put("issuingDate", idResult.getIssuingDate());
                        credentialMap.put("expiryDate", idResult.getExpiryDate());
                        credentialMap.put("issuingCountry", idResult.getIssuingCountry());
                        credentialMap.put("lastName", idResult.getLastName());
                        credentialMap.put("firstName", idResult.getFirstName());
                        credentialMap.put("gender", idResult.getGender());
                        credentialMap.put("nationality", idResult.getNationality());
                        credentialMap.put("dateOfBirth", idResult.getDateOfBirth());

                        credentialMap.put("addressLine", idResult.getAddress());
                        credentialMap.put("city", idResult.getCity());
                        credentialMap.put("subdivision", idResult.getSubdivision());
                        credentialMap.put("postCode", idResult.getPostalCode());
                        credentialMap.put("placeOfBirth", idResult.getPlaceOfBirth());

                        credentialMap.put("mrzLine1", idResult.getMrzLine1());
                        credentialMap.put("mrzLine2", idResult.getMrzLine2());
                        credentialMap.put("mrzLine3", idResult.getMrzLine3());
                    } else if (jumioCredentialResult instanceof JumioFaceResult) {
                        //lowercase
                        credentialMap.put("passed", String.valueOf(((JumioFaceResult) jumioCredentialResult).getPassed()));
                    }
                } catch (JSONException e) {
                    showErrorMessage("Result could not be sent: " + e.getLocalizedMessage());
                }
                credentialsArray.add(credentialMap);
            }
            try {
                result.put("credentials", credentialsArray);
            } catch (JSONException e) {
                showErrorMessage("Result could not be sent: " + e.getLocalizedMessage());
            }
        }
        callbackContext.success(result);
    }

    private void sendCancelResult(final JumioResult jumioResult) {
        if (jumioResult != null && jumioResult.getError() != null) {
            String errorMessage = jumioResult.getError().getMessage();
            String errorCode = jumioResult.getError().getCode();
            sendErrorObject(errorCode, errorMessage);
        } else {
            showErrorMessage("There was a problem extracting the scan result");
        }
    }

    private void showErrorMessage(String msg) {
        Log.e(TAG, msg);
        try {
            JSONObject errorResult = new JSONObject();
            errorResult.put("errorMessage", msg != null ? msg : "");
            if(callbackContext != null) {
                callbackContext.error(errorResult);
            }
        } catch (JSONException e) {
            Log.e(TAG, e.getLocalizedMessage());
        } catch (NullPointerException e) {
            Log.e(TAG, e.getLocalizedMessage());
        }

    private void sendErrorObject(String errorCode, String errorMsg) {
        try {
            JSONObject errorResult = new JSONObject();
            errorResult.put("errorCode", errorMsg != null ? errorCode : "");
            errorResult.put("errorMessage", errorMsg != null ? errorMsg : "");

            if(callbackContext != null) {
                callbackContext.error(errorResult);
            }
        } catch (JSONException e) {
            showErrorMessage("Result could not be sent: " + e.getLocalizedMessage());
        } catch (NullPointerException e) {
            showErrorMessage("Result could not be sent: " + e.getLocalizedMessage());
        }
    }
}
`

At line246 is missing a closing bracket "}" and all those imports I previously mentioned generate further errors:

"capacitor-cordova-android-plugins\src\main\java\com\jumio\mobilesdk\JumioMobileSDK.java:8: error: package com.jumio.cordova.demo does not exist
import com.jumio.cordova.demo.R;"

**Comment by bratapfelmus** [comment]
Without seeing the actual line numbers, the error message `At line246 is missing a closing bracket "}" ` seems fairly obvious? Just form the formatting, seems like:

`private void showErrorMessage(String msg) {...` might be the function missing the bracket.

**Comment by marshall86** [comment]
In the JumioMobileSDK.java file there is import com.jumio.cordova.demo.R;

that causes this error: package com.jumio.cordova.demo does not exist import com.jumio.cordova.demo.R;
therefore even  
"
//The following intent extra can be used to customize the Theme of Default UI intent.putExtra(JumioActivity.EXTRA_CUSTOM_THEME, R.style.AppThemeCustomJumio);
"
fails.

What's the correct import that should be there instead ? Can you fix it please? @bratapfelmus @hrohrweck @kolphi @lukasdanzer 

Sorry for the tags but I need to make it works ASAP

**Comment by bratapfelmus** [comment]
@marshall86 
first of all, please refrain from tagging random Jumio members, especially ones who aren't even mobile devs. 
Second of all, we appreciate that this is urgent for you and we respond and react as fast as we can. However, this Github repo isn't the only item on the list of responsibilities. 

The missing closing bracket is being fixed right now, please keep an eye on the repo for updates. As for the other issues, I've mentioned multiple times already that Ionic isn't something we actively support. It looks like there is a problem with the package import for some reason that is hard to determine with the info we've been given so far -- Invalidate Caches and rebuilding project might help.

**Comment by lukasdanzer** [comment]
Hi @marshall86, 

thanks for bringing this up, we will take care.
Can you please raise this topic in addition to here with at support@jumio.com by linking this issue thread so that we can link your request to your customer account. Our Jumio support is 24/7 and always the right place to reach out to, especially in urgent cases.

**Comment by kolphi** [comment]
@marshall86 
We fixed the missing bracket and commented out the customization via the styles.xml as you can enable it optionally.
Pls check out this commit. Just re-tested and this should work for you too https://github.com/Jumio/mobile-cordova/commit/e9cd91f8ca4b2322d19487f84b3b553acab3bd11 .
There can be Cordova version issues that require an update to targetSDK level 31 and minSDK level to 22, alongside adding:
`android.jetifier.blacklist=bcprov-jdk15on` in the local gradle.properties file. That depends on your Cordova Android version setup.
Customization should work via the jumio-styles.xml file that is injected in the plugin.xml (https://github.com/Jumio/mobile-cordova/blob/e9cd91f8ca4b2322d19487f84b3b553acab3bd11/plugin.xml#L71-L73) and a custom theme that can be overridden there if necessary

**Comment by marshall86** [comment]
@kolphi  ok, just tried it out and in the sdk java file there is another error: this is the correct file
`/*
 * Copyright 2017 Jumio Corporation
 * All rights reserved
 */

package com.jumio.mobilesdk;

import capacitor.android.plugins.R;
import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.util.Log;

import com.jumio.defaultui.JumioActivity;
import com.jumio.sdk.JumioSDK;
import com.jumio.sdk.credentials.JumioCredentialInfo;
import com.jumio.sdk.exceptions.PlatformNotSupportedException;
import com.jumio.sdk.result.JumioCredentialResult;
import com.jumio.sdk.result.JumioFaceResult;
import com.jumio.sdk.result.JumioIDResult;
import com.jumio.sdk.result.JumioResult;

import org.apache.cordova.CallbackContext;
import org.apache.cordova.CordovaPlugin;
import org.apache.cordova.PluginResult;
import org.apache.cordova.PluginResult.Status;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

public class JumioMobileSDK extends CordovaPlugin {

    private static String TAG = "JumioMobileSDK";
    private static final int PERMISSION_REQUEST_CODE = 301;
    private final static int REQUEST_CODE = 101;

    private static final String ACTION_INIT = "initialize";
    private static final String ACTION_START = "start";

    private CallbackContext callbackContext;
    private boolean initiateSuccessful = false;

    @Override
    public boolean execute(String action, JSONArray args, CallbackContext callbackContext) throws JSONException {
        PluginResult result = null;
        this.callbackContext = callbackContext;

        if (action.equals(ACTION_INIT)) {
            initialize(args);
            result = new PluginResult(Status.NO_RESULT);
            result.setKeepCallback(false);
            return true;
        } else if (action.equals(ACTION_START)) {
            start(args);
            result = new PluginResult(Status.NO_RESULT);
            result.setKeepCallback(true);
            return true;
        } else {
            result = new PluginResult(Status.INVALID_ACTION);
            callbackContext.error("Invalid Action");
            return false;
        }
    }

    private void initialize(JSONArray data) {
        if (!JumioSDK.isSupportedPlatform(cordova.getActivity())) {
            showErrorMessage("This platform is not supported.");
            return;
        }

        try {
            if (data.isNull(0) || data.isNull(1)) {
                showErrorMessage("Missing required parameters one-time session authorization token or dataCenter.");
                return;
            }

            final String authorizationToken = data.getString(0);
            final String dataCenter = data.getString(1);

            final Intent intent = new Intent(cordova.getActivity(), JumioActivity.class);
            intent.putExtra(JumioActivity.EXTRA_TOKEN, authorizationToken);
            intent.putExtra(JumioActivity.EXTRA_DATACENTER, dataCenter);

            //The following intent extra can be used to customize the Theme of Default UI
            intent.putExtra(JumioActivity.EXTRA_CUSTOM_THEME, R.style.AppThemeCustomJumio);

            cordova.getActivity().startActivityForResult(intent, REQUEST_CODE);

        } catch (JSONException e) {
            showErrorMessage("Invalid parameters: " + e.getLocalizedMessage());
        }
    }

    private void start(JSONArray data) {
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                try {
                    checkPermissionsAndStart();
                } catch (Exception e) {
                    showErrorMessage("Error starting the Jumio SDK: " + e.getLocalizedMessage());
                }
            }
        };

        this.cordova.setActivityResultCallback(this);
        this.cordova.getActivity().runOnUiThread(runnable);
    }

    // Permissions
    private void checkPermissionsAndStart() {
        if (!JumioSDK.hasAllRequiredPermissions(cordova.getActivity().getApplicationContext())) {
            //Acquire missing permissions.
            String[] mp = JumioSDK.getMissingPermissions(cordova.getActivity().getApplicationContext());

            cordova.requestPermissions(this, PERMISSION_REQUEST_CODE, mp);
        }
    }

    @Override
    public void onRequestPermissionResult(int requestCode, String[] permissions, int[] grantResults) throws
            JSONException {
        boolean allGranted = true;
        for (int grantResult : grantResults) {
            if (grantResult != PackageManager.PERMISSION_GRANTED) {
                allGranted = false;
                break;
            }
        }

        if (!allGranted) {
            showErrorMessage("You need to grant all required permissions to continue");
            super.onRequestPermissionResult(requestCode, permissions, grantResults);
        }
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == REQUEST_CODE) {
            if (data == null) {
                return;
            }

            final JumioResult jumioResult = (JumioResult) data.getSerializableExtra(JumioActivity.EXTRA_RESULT);

            if (jumioResult != null && jumioResult.isSuccess()) {
                sendScanResult(jumioResult);
            } else {
                sendCancelResult(jumioResult);
            }
        }
    }

    private void sendScanResult(final JumioResult jumioResult) {
        final String accountId = jumioResult.getAccountId();
        final List<JumioCredentialInfo> credentialInfoList = jumioResult.getCredentialInfos();

        final JSONObject result = new JSONObject();
        final ArrayList<JSONObject> credentialsArray = new ArrayList<>();


        if (credentialInfoList != null) {
            try {
                if (accountId != null) {
                    result.put("accountId", accountId);
                }
            } catch (JSONException e) {
                showErrorMessage("Result could not be sent: " + e.getLocalizedMessage());
            }

            for (JumioCredentialInfo credentialInfo : credentialInfoList) {
                final JumioCredentialResult jumioCredentialResult = jumioResult.getResult(credentialInfo);
                final JSONObject credentialMap = new JSONObject();
                try {
                    credentialMap.put("credentialId", credentialInfo.getId());
                    credentialMap.put("credentialCategory", credentialInfo.getCategory().toString());


                    if (jumioCredentialResult instanceof JumioIDResult) {
                        final JumioIDResult idResult = (JumioIDResult) jumioCredentialResult;
                        credentialMap.put("selectedCountry", idResult.getCountry());
                        credentialMap.put("selectedDocumentType", idResult.getIdType());
                        credentialMap.put("idNumber", idResult.getDocumentNumber());
                        credentialMap.put("personalNumber", idResult.getPersonalNumber());
                        credentialMap.put("issuingDate", idResult.getIssuingDate());
                        credentialMap.put("expiryDate", idResult.getExpiryDate());
                        credentialMap.put("issuingCountry", idResult.getIssuingCountry());
                        credentialMap.put("lastName", idResult.getLastName());
                        credentialMap.put("firstName", idResult.getFirstName());
                        credentialMap.put("gender", idResult.getGender());
                        credentialMap.put("nationality", idResult.getNationality());
                        credentialMap.put("dateOfBirth", idResult.getDateOfBirth());

                        credentialMap.put("addressLine", idResult.getAddress());
                        credentialMap.put("city", idResult.getCity());
                        credentialMap.put("subdivision", idResult.getSubdivision());
                        credentialMap.put("postCode", idResult.getPostalCode());
                        credentialMap.put("placeOfBirth", idResult.getPlaceOfBirth());

                        credentialMap.put("mrzLine1", idResult.getMrzLine1());
                        credentialMap.put("mrzLine2", idResult.getMrzLine2());
                        credentialMap.put("mrzLine3", idResult.getMrzLine3());
                    } else if (jumioCredentialResult instanceof JumioFaceResult) {
                        //lowercase
                        credentialMap.put("passed", String.valueOf(((JumioFaceResult) jumioCredentialResult).getPassed()));
                    }
                } catch (JSONException e) {
                    showErrorMessage("Result could not be sent: " + e.getLocalizedMessage());
                }
                credentialsArray.add(credentialMap);
            }
            try {
                result.put("credentials", credentialsArray);
            } catch (JSONException e) {
                showErrorMessage("Result could not be sent: " + e.getLocalizedMessage());
            }
        }
        callbackContext.success(result);
    }

    private void sendCancelResult(final JumioResult jumioResult) {
        if (jumioResult != null && jumioResult.getError() != null) {
            String errorMessage = jumioResult.getError().getMessage();
            String errorCode = jumioResult.getError().getCode();
            sendErrorObject(errorCode, errorMessage);
        } else {
            showErrorMessage("There was a problem extracting the scan result");
        }
    }

    private void showErrorMessage(String msg) {
        Log.e(TAG, msg);
        try {
            JSONObject errorResult = new JSONObject();
            errorResult.put("errorMessage", msg != null ? msg : "");
            if (callbackContext != null) {
                callbackContext.error(errorResult);
            }
        } catch (JSONException e) {
            Log.e(TAG, e.getLocalizedMessage());
        } catch (NullPointerException e) {
            Log.e(TAG, e.getLocalizedMessage());
        }

    }

    private void sendErrorObject(String errorCode, String errorMsg) {
        try {
            JSONObject errorResult = new JSONObject();
            errorResult.put("errorCode", errorMsg != null ? errorCode : "");
            errorResult.put("errorMessage", errorMsg != null ? errorMsg : "");

            if(callbackContext != null) {
                callbackContext.error(errorResult);
            }
        } catch (JSONException e) {
            showErrorMessage("Result could not be sent: " + e.getLocalizedMessage());
        } catch (NullPointerException e) {
            showErrorMessage("Result could not be sent: " + e.getLocalizedMessage());
        }
    }
}
`
unfortunately when I try to run it on the device I get "plugin_not_installed" error

I'm using Android gradle plugin version 7.0.3 and Android Gradle 7.0.2

buildToolsVersion '31.0.0' 

this is my variable.gradle:

ext {
    minSdkVersion = 23
    compileSdkVersion = 31
    targetSdkVersion = 31
    androidxAppCompatVersion = '1.4.1'
    androidxCoreVersion =  '1.2.0'
    androidxMaterialVersion =  '1.1.0-rc02'
    androidxBrowserVersion =  '1.2.0'
    androidxLocalbroadcastmanagerVersion =  '1.0.0'
    androidxExifInterfaceVersion = '1.2.0'
    firebaseMessagingVersion =  '20.1.2'
    playServicesLocationVersion =  '17.0.0'
    junitVersion =  '4.12'
    androidxJunitVersion =  '1.1.1'
    androidxEspressoCoreVersion =  '3.2.0'
    cordovaAndroidVersion =  '10.0.0'
}

**Comment by kolphi** [comment]
As Lukas mentioned above, please reach out to support@jumio.com so we can track and document this issue properly.

It would be easier if you could maybe fork the repository and add the respective adaptions for capacitor there. It's more effort to diff the changes if you paste the code here. You reverted some of the changes and added the optional customization again compared to the last commit as what I see.
Does a classic Cordova build for the Demo app work at least on your end now?

Please add more build error details to the support request if possible. The message "plugin not installed" could be also something Capacitor-related or anything else which we can't resolve.
The versions posted in the variable.gradle seem a bit outdated. Especially "1.1.0-rc02" of the Material lib. This could cause additional issues. Our dependencies are resolved transitively, but you can check the used versions here https://github.com/Jumio/mobile-sdk-android/blob/master/docs/transition_guide.md#400 or in the respective pom.xml files

**Comment by bratapfelmus** [comment]
Hello @marshall86 

- About optional customization, I assume @kolphi was referring to this line being uncommented and therefore "added" in the code you shared in the comment above: `intent.putExtra(JumioActivity.EXTRA_CUSTOM_THEME, R.style.AppThemeCustomJumio);`
- `startSdk()` method is not missing, some things were re-written for plugin version 4.0.0 since there is now only one universal SDK instead of BAM, Netverify and DV 
- Are there any warnings when trying to install the plugin? (Versions not being compatible, etc...) If you run `cordova plugin list` do you see the plugin? 
- Please contact support with as much added detail as possible -- exact steps you're taking to add the plugin, potential changes you've made, findings from the previous steps, etc...

**Comment by marshall86** [comment]
The plugin is listed but there might be something missing in Ionic or capacitor to make the sdk working properly.
To use your plugin ionic has a an ionic-native/jumio plugin but it still uses the old method like "initNetverify" ecc this doesn't help either I guess.

I will try it again later on, for now I have to stick to sdk 3.9.2 that seems to be fine. Much appreciate your help
