### ISSUE TITLE
Jumio 3.9.2 (initNetverify) not working on UAT or Prod

### ISSUE THREAD

**Issue by Dav418** [Jumio/mobile-cordova#12]
Hi guys,

Recently jumio stopped working in my cordova project. I have isolated the issue and I am pretty confident that this is the issue

https://github.com/Jumio/mobile-sdk-ios/blob/master/docs/known_issues.md#sdk-version-not-compatible-after-xcode-13-update

Unfortunately, my problem here is that I have no idea how to edit this in Cordova, since I use fastlane to build ios and android and everytime that the app is build for UAT or Prod, the exportOptions.plist is overwritten

Would it be possible to do this in config.xml? If not could you advise on what would be the best course of action? 

Many thanks,
Dav

**Comment by bratapfelmus** [comment]
Hello @Dav418 
please contact Jumio support!
