### ISSUE TITLE
Android: Execution failed for task ':app:checkDebugDuplicateClasses'.

### ISSUE THREAD

**Issue by shahdeep1989** [Jumio/mobile-cordova#14]
Hi,

Facing below error while creating android build.

> Task :app:checkDebugDuplicateClasses FAILED
aapt2 W 10-13 18:06:06 19238 415098 LoadedArsc.cpp:682] Unknown chunk type '200'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform bcprov-jdk18on-1.71.jar (org.bouncycastle:bcprov-jdk18on:1.71) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/deepshah/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk18on/1.71/943e8d0c2bd592ad78759c39d6f749fafaf29cf4/bcprov-jdk18on-1.71.jar.
         > Failed to transform '/Users/deepshah/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk18on/1.71/943e8d0c2bd592ad78759c39d6f749fafaf29cf4/bcprov-jdk18on-1.71.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
32 actionable tasks: 4 executed, 28 up-to-date
Command failed with exit code 1: /platforms/android/gradlew cdvBuildDebug -b /platforms/android/build.gradle

deepshah$ cordova -v
11.0.0

deepshah$ cordova platform ls
Installed platforms:
  android 10.1.2

deepshah$ gradle -v
Gradle 7.5.1
Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918
Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.15 (Homebrew 11.0.15+0)
OS:           Mac OS X 11.6.5 x86_64

deepshah$ java -version
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Homebrew (build 11.0.15+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.15+0, mixed mode)

deepshah$ javac -version
javac 11.0.15

**Comment by BernadetteTh** [comment]
Hello @shahdeep1989 
if this issue has not been resolved yet, this might help --> https://github.com/Jumio/mobile-sdk-android/blob/master/docs/known_issues.md#jetifier-issues
