### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by marshall86** [Jumio/mobile-cordova#16]
I downloaded your demo project to check how the latest plugin version should work but I keep getting the error: "authentication failed error code c10401".  I correctly get a token from here https://auth.emea-1.jumio.ai/oauth2/token and I'm using "EU" as data center.

Any advice on how to fix it please?

I also noticed that you have a wrong reference here (https://github.com/Jumio/mobile-cordova/tree/master/src/android)/JumioMobileSDK.kt at line 6 that should be replaced with 'import capacitor.android.plugins.R'

Besides, there are a couple of references to deprecated methods like "super.onRequestPermissionResult(requestCode, permissions, grantResults)' (line 65) and   cordova.activity.startActivityForResult(intent, REQUEST_CODE);
(line 110)

**Comment by BernadetteTh** [comment]
Hello @marshall86 
could you provide more details on how you are obtaining your `sdk.token`?

**Comment by BernadetteTh** [comment]
In this case, please contact support with the following information: 

- Which SDK plugin version you're updating from
- If this works fine for iOS and the issue only affects Android or not
- That OAuth2 is enabled for your account and CLIENTID / CLIENTSECRET were taken from the `OAuth2 Clients` tab in the customer portal 
- If this is reproducible with the demo app
- If possible, provide a `sdk.token` you have created (please make sure to set a longer token lifetime, e.g. a few days at least) so we can test on our end

**Comment by lbras** [comment]
I'm having the exact same issue with the demo app and with another app I'm upgrading from Jumio v3.9.2 to v4.5.0. When the SDK is initialized, I get the error: "Connection error, authentication failed (C010401)":

`Jumio.initialize(<AUTHORIZATION_TOKEN>, <DATACENTER>);`

It is also on Android and EU datacenter.

Waiting for a response from support. Did you manage to overcome the issue @marshall86?

**Comment by marshall86** [comment]
> I'm having the exact same issue with the demo app and with another app I'm upgrading from Jumio v3.9.2 to v4.5.0. When the SDK is initialized, I get the error: "Connection error, authentication failed (C010401)":
> 
> `Jumio.initialize(<AUTHORIZATION_TOKEN>, <DATACENTER>);`
> 
> It is also on Android and EU datacenter.
> 
> Waiting for a response from support. Did you manage to overcome the issue @marshall86?

Unfortunately, I didn't manage yet.. They weren't helpful. Please let me know if you manage to fix the issue.. For now I'm still using 392 but I should upgrade the version sooner or later

**Comment by BernadetteTh** [comment]
Hello @marshall86 
just looked up your ticket internally (Devere Group, Cordova ionic implementation, please let me know if this is incorrect) and it closed due to inactivity. Last state was a request to share some details, which didn't seem to get a response. 
If you would like to respond, please contact our support. Your internal IPM number is IPM-9599. 

@lbras 
please contact Jumio support with the following information:

* Is OAuth2 enabled for your account and were CLIENTID / CLIENTSECRET taken from the OAuth2 Clients tab in the customer portal
* If this is reproducible with the demo app
* If possible, provide a sdk.token you have created (please make sure to set a longer token lifetime, e.g. a few days at least) so we can test on our end

**Comment by marshall86** [comment]
Hi @BernadetteTh , what are the info you need?

**Comment by BernadetteTh** [comment]
Hi @marshall86 
just checked back in and looks like your ticket got closed due to inactivity back in April. 
Please look into the response you should have gotten on this from Jumio support and/or feel free to contact again and have it reopened.
