### ISSUE TITLE
Implementing fix for known issue in a Cordova environment

### ISSUE THREAD

**Issue by Noteofman** [Jumio/mobile-cordova#5]
Hi,

There is an outstanding issue on the iOS sdk noted here:
https://github.com/Jumio/mobile-sdk-ios/blob/master/docs/known_issues.md

Specifically:
_dyld: Symbol not found: $s8SocketIO0A11ClientEventO10disconnectyA2CmFWC
Referenced from: /Users/.../Frameworks/iProov.framework/iProov
Expected in: /Users/b.../Frameworks/SocketIO.framework/SocketIO in /Users/.../Frameworks/iProov.framework/iProov

The listed fix is to add a hook into your Podfile, however as you know this isn't as easy to do in a Cordova environment as with Cordova applications, the standard practice is to not commit platform directories, as well as that you should not modify the PodFile generated by cordova as it will be overwritten, as stated in the line "# DO NOT MODIFY -- auto-generated by Apache Cordova" at the top of the file. Is there a recommend way to implement this fix into a cordova environment without sacrificing best practises?

Thanks.

**Comment by bratapfelmus** [comment]
Hi @Noteofman, 

modifying the podfile is the only short term solution for now, yes. 

The only way the auto generated files (e.g. the podfile) get overwritten in this case is if ios as a platform is removed and then added again. Adding the platforms is a step that should happen only once at the beginning, in the process of creating a new Cordova project. (See [setup steps](https://github.com/Jumio/mobile-cordova#setup).)

Of course it's not best practice and we'll improve this in the future, but for now, adding the install hook to the podfile is the solution. 

There is also the possibility of using Cordova hooks to run the post install hook using the plugin.xml, which might be something worth looking into: https://cordova.apache.org/docs/en/10.x/guide/appdev/hooks/index.html

**Comment by farxelemon** [comment]
Hi @Noteofman ,

Did you manage to overcome this problem with a Cordova hook? If so, can you share your hook file?

Best regards.
