### ISSUE TITLE
Customization on Android

### ISSUE THREAD

**Issue by dwlrathod** [Jumio/mobile-cordova#6]
For the Android version, how can we customize the theme if we don't have access to the manifest or styles as suggested in the [tutorial](https://github.com/Jumio/mobile-sdk-android/blob/v3.9.1/docs/integration_id-verification-fastfill.md#tutorial-1)?

I am using a plugin with Ionic Capacitor.

**Comment by bratapfelmus** [comment]
Hi @dwlrathod, 
using the `<platform name="android">` tag in the `config.xml` file might be an option for you in this case? 

https://www.npmjs.com/package/cordova-custom-config#android-example
https://www.npmjs.com/package/cordova-custom-config#android-config-blocks

**Comment by bratapfelmus** [comment]
Closing this issue.
