### ISSUE TITLE
Cancelled with exception DocumentVerificationInstanceNotDestroyed

### ISSUE THREAD

**Issue by KimViktor** [Jumio/mobile-cordova#9]
**OS**: iOS
**Plugin** [version v3.9.2](https://github.com/Jumio/mobile-cordova/tree/v3.9.2
)

`Jumio.initDocumentVerification()` throws an error if trying to call document verification several times.

```
DocumentVerification::init Error: {"errorMessage":"Cancelled with exception DocumentVerificationInstanceNotDestroyed: There is another DocumentVerification instance available. Dealocate the instance before creating a new one!"}
```

![image](https://user-images.githubusercontent.com/43338908/149234305-59726f68-aea4-47fd-bca7-f9b51b8bf31d.png)

Is there any ability to destroy `DocumentVerification` instance without hacking the plugin?

**Comment by bratapfelmus** [comment]
Hello @KimViktor 
at the moment, there is no `destroy` (or equivalent) method exposed in the Cordova plugin. 
If this is an issue, please contact support with details on your setup -- at which exact point(s) is the SDK initialized, how often, reasons why it needs to be called several times in a row, etc. ...

**Comment by KimViktor** [comment]
Hello @bratapfelmus 

Thanks for your answer. Submitted request in customer support.
